name: Release Python Package

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'source/ports/py_port/VERSION'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release Python Port
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release the port
        env:
          PYTHON_PYPI_USER: ${{ secrets.PYTHON_PYPI_USER }}
          PYTHON_PYPI_PASSWORD: ${{ secrets.PYTHON_PYPI_PASSWORD }}
        run: |
          cd source/ports/py_port
          bash ./upload.sh
